Post.create(title: 'My first post', author: 'Tyson Van Buren', description: 'This is my bad A post get it got it want some more of it')
Post.create(title: 'My second post', author: 'Tyson Van Buren', description: 'This is my bad A post get it got it want some more of it')
Post.create(title: 'My third post', author: 'Tyson Van Buren', description: 'This is my bad A post get it got it want some more of it')
Post.create(title: 'My fourth post', author: 'Tyson Van Buren', description: 'This is my bad A post get it got it want some more of it')
Post.create(title: 'My fifth post', author: 'Tyson Van Buren', description: 'This is my bad A post get it got it want some more of it')
Post.create(title: 'My final post', author: 'Tyson Van Buren', description: 'This is my bad A post get it got it want some more of it')
